
version: '2'

volumes:
  orderer.health-network.com:
  peer0.HM.health-network.com:
  peer0.FM.health-network.com:
  peer0.EM.health-network.com:
  peer0.P.health-network.com:


networks:
  network:

services:

  orderer.health-network.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.health-network.com
    container_name: orderer.health-network.com
    networks:
      - network

  peer0.HM.health-network.com:
    container_name: peer0.HM.health-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.HM.health-network.com
    networks:
      - network

  
  peer0.FM.health-network.com:
    container_name: peer0.FM.health-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.FM.health-network.com
    networks:
      - network

  peer0.EM.health-network.com:
    container_name: peer0.EM.health-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.EM.health-network.com
    networks:
      - network

  peer0.P.health-network.com:
    container_name: peer0.P.health-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.P.health-network.com
    networks:
      - network      
 
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.3
    tty: true
    stdin_open: true
    dns_search: .
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      #- CORE_LOGGING_LEVEL=INFO
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.HM.health-network.com:7051
      - CORE_PEER_LOCALMSPID=HealthMinistryMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/fabric-samples/health-network/crypto-config/peerOrganizations/HM.health-network.com/peers/peer0.HM.health-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/fabric-samples/health-network/crypto-config/peerOrganizations/HM.health-network.com/peers/peer0.HM.health-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/fabric-samples/health-network/crypto-config/peerOrganizations/HM.health-network.com/peers/peer0.HM.health-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/fabric-samples/health-network/crypto-config/peerOrganizations/HM.health-network.com/users/Admin@HM.health-network.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/chain
        - ./crypto-config:/opt/gopath/fabric-samples/health-network/crypto-config/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/fabric-samples/health-network/channel-artifacts
        - ./application:/opt/gopath/fabric-samples/health-network/application
        

    depends_on:
      - orderer.health-network.com
      - peer0.HM.health-network.com
      - peer0.FM.health-network.com
      - peer0.EM.health-network.com
      - peer0.P.health-network.com
      
    networks:
      - network
